Member.create(name:"すぎうら", account: "Izumi_Konata", achievement: "")
Member.create(name:"ぷく", account: "kenokohe", achievement: "現役奨励会有段")
Member.create(name:"ほっしー", account: "Aleister_Crowley", achievement: "元奨、全国優勝2回、プロ棋戦出場経験有")
Member.create(name:"あつと", account: "endo_sakura", achievement: "現役奨励会４級")
Member.create(name:"しゅん", account: "Ohashi Keika", achievement: "現役奨励会三段")
Member.create(name:"しゅうまい", account: "shushu2016", achievement: "現役奨励会員")

Result.create(member_id:1, op_id:1)
Result.create(member_id:1, op_id:2)
Result.create(member_id:1, op_id:3)
Result.create(member_id:1, op_id:4)
Result.create(member_id:1, op_id:5)
Result.create(member_id:1, op_id:6)

Result.create(member_id:2, op_id:1)
Result.create(member_id:2, op_id:2)
Result.create(member_id:2, op_id:3)
Result.create(member_id:2, op_id:4)
Result.create(member_id:2, op_id:5)
Result.create(member_id:2, op_id:6)

Result.create(member_id:3, op_id:1)
Result.create(member_id:3, op_id:2)
Result.create(member_id:3, op_id:3)
Result.create(member_id:3, op_id:4)
Result.create(member_id:3, op_id:5)
Result.create(member_id:3, op_id:6)

Result.create(member_id:4, op_id:1)
Result.create(member_id:4, op_id:2)
Result.create(member_id:4, op_id:3)
Result.create(member_id:4, op_id:4)
Result.create(member_id:4, op_id:5)
Result.create(member_id:4, op_id:6)

Result.create(member_id:5, op_id:1)
Result.create(member_id:5, op_id:2)
Result.create(member_id:5, op_id:3)
Result.create(member_id:5, op_id:4)
Result.create(member_id:5, op_id:5)
Result.create(member_id:5, op_id:6)

Result.create(member_id:6, op_id:1)
Result.create(member_id:6, op_id:2)
Result.create(member_id:6, op_id:3)
Result.create(member_id:6, op_id:4)
Result.create(member_id:6, op_id:5)
Result.create(member_id:6, op_id:6)